### ISSUE TITLE
API DELETE Route in Chapter 5 not working as intended

### ISSUE THREAD

**Issue by hjkrannig** [PacktPublishing/Modern-Web-Development-with-the-FARM-Stack#4]
Hi, there is a problem with the DELETE-request in the car-API in chapter5. The car is deleted as expected, but an Error is raised: "Too much data for declared Content-Length:"
The last line from server-output is:
###
  File "/home/hjkrannig/Development/js/farm/first-stack/be_cars/vbecars/lib/python3.8/site-packages/h11/_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
###

The line with the JSONResponse in my code is exactly like the one here in github:
###
    if delete_result.deleted_count == 1:
        return JSONResponse(status_code=status.HTTP_204_NO_CONTENT, content=None)
###

There is a known bug in stackoverflow, but I can't fix it.

**Comment by freethrow** [comment]
I am afraid that the problem is bigger than this example: https://github.com/tiangolo/fastapi/issues/2832
You have probably seen this. I'll take a look and see if there is a solution.

We could of course set a custom JSON message like "deleted successfully" and return a regular 200, but that is not what we want...

**Comment by hjkrannig** [comment]
Ohh, Thanks again, but I could fix it. I will send you my code-solution
tomorrow.
Greetings hjk

Freethrow aka Marko ***@***.***> schrieb am Mi., 23. Nov.
2022, 20:18:
